FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy solution and project files
COPY *.sln ./
COPY DatabaseRepl/*.csproj ./DatabaseRepl/
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish DatabaseRepl/DatabaseRepl.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "DatabaseRepl.dll"]